name: disco
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - rdkit=2023.09.4
  - pip:
      - torch==1.13.1+cu117
      - torchvision==0.14.1+cu117
      - torchaudio==0.13.1
      - torch-geometric==2.2.0
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-cluster==1.6.1
      - torch-spline-conv==1.2.2
      - numpy==1.25.0
      - pyemd==1.0.0
      - torchmetrics==1.2.1
